package com.example.quizz.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ErrorCode {
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR,1000,"SOMETHING IS WRONG!"),
    USERNAME_ALREADY_EXISTS(HttpStatus.CONFLICT,1001,"USERNAME ALREADY EXISTS!"),
    TOPIC_NOT_FOUND(HttpStatus.NOT_FOUND,1002,"TOPIC NOT FOUND!"),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND,1003,"CATEGORY NOT FOUND!"),
    TOPIC_IS_EMPTY(HttpStatus.NOT_FOUND,1004,"TOPIC IS EMPTY"),
    QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND,1005,"QUESTION NOT FOUND!"),
    QUESTION_IS_EMPTY(HttpStatus.NOT_FOUND,1006,"QUESTION IS EMPTY"),
    ANSWERS_ARRAY_EMPTY(HttpStatus.BAD_REQUEST,1007,"ANSWERS ARRAY CANNOT BE EMPTY!"),
    QUESTIONS_ARRAY_EMPTY(HttpStatus.BAD_REQUEST,1008,"QUESTION ARRAY CANNOT BE EMPTY!"),
    UPLOAD_FILE_FAIL(HttpStatus.BAD_REQUEST,1009,"UPLOAD FILE FAIL!"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND,1010,"USERNAME MOT FOUND!"),
    METHOD_ARGUMENT_NOT_VALID(HttpStatus.BAD_REQUEST,1011,"METHOD_ARGUMENT_NOT_VALID"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT,1012,"EMAIL ALREADY EXISTS!"),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED,1013,"YOU NEED TO LOGIN!"),
    UNAUTHORIZED(HttpStatus.FORBIDDEN,1014,"YOU NEED PERMISSION!"),
    WRONG_USERNAME_OR_PASSWORD(HttpStatus.UNAUTHORIZED,1015,"WRONG USERNAME OR PASSWORD!"),
    ;
    private HttpStatus httpStatus;
    private int code;
    private String message;

}
